package com.dashboard.api.service.acesso;

public enum AcaoAudit {
    LOGIN,
    LOGIN_FALHA,
    LOGOUT,
    SENHA_ALTERADA,
    USUARIO_CRIADO,
    USUARIO_ATUALIZADO,
    USUARIO_DESATIVADO,
    USUARIO_EXCLUIDO,
    PAPEL_CONCEDIDO,
    PAPEL_REVOGADO,
    PERMISSAO_OVERRIDE_ALTERADA,
    SETOR_CRIADO,
    SETOR_ATUALIZADO,
    SETOR_EXCLUIDO,
    CONTA_BLOQUEADA,
    CONTA_DESBLOQUEADA,
    RATE_LIMIT_EXCEDIDO
}
