-- No-op intencional.
-- O Dashboard nao cria nem sincroniza wrappers de views pertencentes ao ETL.
-- O contrato de dbo.vw_fretes_powerbi deve ser publicado pelo owner do ETL e apenas consumido aqui.
